#用于选择配置文件，开发时通过active指向开发环境  dev
#生产环境指向  prod

spring:
  profiles:
    active: dev
#以下配置,dev和prod都可以使用（公用配置写在application.yml文件里面）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
#    create:每次都将表重新创建，表里面的数据会丢失
      ddl-auto: update
    show-sql: true


  redis:
      host: localhost
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1

  # mybatis配置
  mybatis:
    # 配置映射类所在包名
    type-aliases-package: com.zuoqing.demo.entity
    # 配置mapper xml文件所在路径，这里是一个数组
    mapper-locations: classpath:mapper/*.xml