package com.zuoqing.demo.dao;

import com.zuoqing.demo.entity.DemoGirl;
import com.zuoqing.demo.entity.DemoGirlExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface DemoGirlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int countByExample(DemoGirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int deleteByExample(DemoGirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int insert(DemoGirl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int insertSelective(DemoGirl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    List<DemoGirl> selectByExample(DemoGirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    DemoGirl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DemoGirl record, @Param("example") DemoGirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DemoGirl record, @Param("example") DemoGirlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemoGirl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DemoGirl record);
}